### ISSUE TITLE
Project Does not Build in VSC

### ISSUE THREAD

**Issue by AlanJHancock** [frameworklabs/ranger#1]
The project will not build under Platformio the content of file ./lib/blechdeps/blech/ranger.h is not correctly defined it should I believe be an include definition  #include "./lib/blech/ranger.h" but that creates a circular dependency. So something is wrong with the structure of this project.

**Comment by frameworklabs** [comment]
Hi Alan, for testing your issue I freshly cloned the repo and opened the ranger folder in VSC (PlatformIO) - building from there finished successfully without errors. 
The file "./lib/blechdeps/blech/ranger.h" is a symlink to "./lib/blech/ranger.h". I am building on macOS - maybe this makes a difference?
I will try to see if I can remove that symlink in my setup.

**Comment by frameworklabs** [comment]
Hi Alan, I pushed a version which removes the symlink - hope it works for you now. Sorry for the inconvenience.

**Comment by AlanJHancock** [comment]
Thanks for the correction, I am running VSC(PlatformIO) on Windows 10 Home
Device name	LAPTOP-O5HI1V71
Processor	Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz   2.40 GHz
Installed RAM	8.00 GB (7.89 GB usable)
Device ID	31D0FE00-7486-4328-9AA3-C249EE2C3EAA
Product ID	00325-96172-44235-AAOEM
System type	64-bit operating system, x64-based processor

I have tried several times to build Ranger but it seems to get stuck thrashing hard disc at the point below:
Compiling .pio\build\m5stick-c\FrameworkArduino\wiring_shift.c.o
Archiving .pio\build\m5stick-c\libFrameworkArduino.a
Linking .pio\build\m5stick-c\firmware.elf
Any idea what might cause this?

**Comment by AlanJHancock** [comment]
In case PIO under VSC is a problem then I ran the build from the Windows command line, unfortunately, the process still hangs thrashing the disc  at step below: 

Linking .pio\build\m5stick-c\firmware.elf
